# Generated by Django 5.0.4 on 2026-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDAQueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('endpoint', models.CharField(max_length=60)),
                ('query_params', models.JSONField()),
                ('response_data', models.JSONField()),
                ('total_results', models.IntegerField(default=0)),
                ('ttl_expires', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fda_query_cache',
                'indexes': [models.Index(fields=['endpoint', 'ttl_expires'], name='fda_query_c_endpoin_1e7c1a_idx')],
            },
        ),
    ]
