# Generated by Django 5.0.4 on 2026-02-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nl_prompt', models.TextField()),
                ('generated_query', models.JSONField(blank=True, null=True)),
                ('endpoint_used', models.CharField(blank=True, max_length=60)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_query_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
